name: Update Repository

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set Up Poetry
        run: curl -sSL https://install.python-poetry.org | python - --version=$(cat .poetry-version)

      - name: Install Dependencies
        run: poetry install --only main

      - name: Run Scraper
        run: poetry run labosphere start
