name: Update Repository

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: labosphere
  cancel-in-progress: true

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Get Update Branch UUID
        run: |
          import os
          import uuid

          print(uuid.uuid4(), file=open(os.getenv("GITHUB_ENV")))
        shell: python

      - name: Create Update Branch
        run: |
          git branch -f update/${{ env.BRANCH_UUID }}
          git checkout update/${{ env.BRANCH_UUID }}
          git push -u origin update/${{ env.BRANCH_UUID }}
          git branch --set-upstream-to=origin/update/${{ env.BRANCH_UUID }}

      - name: Set Up Poetry
        run: curl -sSL https://install.python-poetry.org | python - --version=$(cat .poetry-version)

      - name: Install Dependencies
        run: poetry install --only main

      - name: Run Labosphere
        run: poetry run labosphere start

      - name: Merge Update Branch
        run: gh pr merge --squash --delete-branch --auto update/${{ env.BRANCH_UUID }}
        env:
          GH_TOKEN: ${{ github.token }}
