name: Update Repository

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}

      - name: Create Update Branch
        run: |
          git branch -f update/${{ github.sha }} 
          git checkout update/${{ github.sha }}
          git push -u origin update/${{ github.sha }}
          git branch --set-upstream-to=origin/update/${{ github.sha }}

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set Up Poetry
        run: curl -sSL https://install.python-poetry.org | python - --version=$(cat .poetry-version)

      - name: Install Dependencies
        run: poetry install --only main

      - name: Run Labosphere
        run: poetry run labosphere start

      - name: Merge Update Branch
        run: gh pr merge --squash --delete-branch --auto --merge update/${{ github.sha }}
        env:
          GH_TOKEN: ${{ github.token }}
