name: Update Repository

on:
  schedule:
    - cron: "0 10,22 * * *"

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: labosphere
  cancel-in-progress: true

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Name Update Branch
        run: |
          import os
          import uuid

          print(f"UPDATE_BRANCH=update/{uuid.uuid4()}", file=open(os.getenv("GITHUB_ENV"), "a"))
        shell: python

      - name: Create Update Branch
        run: |
          git branch -f ${{ env.UPDATE_BRANCH }}
          git checkout ${{ env.UPDATE_BRANCH }}
          git push -u origin ${{ env.UPDATE_BRANCH }}
          git branch --set-upstream-to=origin/${{ env.UPDATE_BRANCH }}

      - name: Set Up Poetry
        run: curl -sSL https://install.python-poetry.org | python - --version=$(cat .poetry-version)

      - name: Install Dependencies
        run: poetry install --only main

      - name: Run Labosphere
        run: poetry run labosphere start

      - name: Merge Update Branch
        run: |
          gh pr create --title "Update repository" --body ""
          gh pr merge --squash --delete-branch --auto ${{ env.UPDATE_BRANCH }}
        env:
          GH_TOKEN: ${{ github.token }}
