name: Post to Webhook

on:
  pull_request:
    types: [closed]

jobs:
  get_commit:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Save Current Cubari
        run: |
          import os

          with open(os.getenv("GITHUB_ENV"), "a") as env:
              print(f"CUBARI={open('cubari.json').read()}", file=env)

      - name: Get Commit Before Merge
        run: |
          git fetch --depth=2
          COMMIT_BEFORE_MERGE=$(git rev-parse HEAD^)
          echo "COMMIT_BEFORE_MERGE=$COMMIT_BEFORE_MERGE" >> $GITHUB_ENV

      - name: Checkout Commit Before Merge
        uses: actions/checkout@v3
        with:
          ref: ${{ env.COMMIT_BEFORE_MERGE }}

      - name: Install Requests
        run: pip install requests

      - name: Post to Webhook
        shell: python
        run: |
          import json
          import requests
          import os

          past_cubari = json.load(open("cubari.json"))
          current_cubari = json.loads(os.getenv("CURRENT_CUBARI"))

          if len(current_cubari["chapters"]) > len(past_cubari["chapters"]):
              chapter_number = list(current_cubari["chapters"].keys())[-1]
              chapter_title = current_cubari["chapters"][chapter_number]["title"]
              
              message = f"""
              *One Piece* Chapter {chapter_number}: "{chapter_title}" has been released by TCB Scans.
              
              https://punkrecords.celsiusnarhwal.dev/{chapter_number}
              """
              
              requests.post(
                  os.getenv("WEBHOOK_URL"),
                  headers={"Content-Type": "application/json"},
                  data={"content": message}
              )
